name: My Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tgcrypto
        pip install -r requirements.txt

    - name: Run Bot
      run: python main.py
      env:
        TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
        INDEED_API_KEY: ${{ secrets.INDEED_API_KEY }}
